### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by chrisyfrisky** [DeGrandis/canvas-dark-mode#28]
I searched for anything regarding Firefox support and didn't find any. So I'll ask it myself. Are there any plans to support this extension for Firefox?

**Comment by DeGrandis** [comment]
I currently do not have the bandwidth to make the changes necessary to get this to work.  There is a chance that it could work already since it's such a simple plugin.  Maybe try looking into loading dev add-ons in firefox and see if it works.  If changes need to be made, and someone makes them, I will review the PR and work on publishing it to the add-on store.  Let me know what you find.

**Comment by chrisyfrisky** [comment]
Well, according to [this guide](https://www.pubgenius.io/2022/02/24/porting-your-chrome-extension-to-firefox/) you can apparently just upload the CRX to the Firefox add-on store and submit the extension if it's compatible with Firefox. And if you check the CRX for Firefox compatibility using [this website](https://www.extensiontest.com/), it says it's compatible. I haven't managed to convert the CRX to an XPI (Firefox extension format) so I can't test it in Firefox, but this does seem promising. And it seems really easy if all *you* have to do is just upload the CRX to [addons.mozilla.org](https://addons.mozilla.org/).

**Comment by chrisyfrisky** [comment]
Okay, so after a lot of finagling, I managed to install it and can confirm that it works on Firefox, by doing the following:

1. Obtain CRX. (This repository doesn't seem to publish any releases, which is out of the ordinary as other extension repositories publish releases containing their compiled extension files, so I just used [crxextractor.com](https://crxextractor.com/) to extract the extension from the Chrome web store.)
2. Realize that XPIs are just ZIPs. (Why name them XPIs? I don't know, Mozilla logic.) So the first step to converting the CRX to XPI is converting the CRX to ZIP. (I just used [ezyzip.com](https://www.ezyzip.com/convert-crx-to-zip.html).)
3. Follow this [Mozilla guide](https://hacks.mozilla.org/2015/10/porting-chrome-extensions-to-firefox-with-webextensions/), except for the parts where it's a bit outdated.
4. The guide says to add the `applications` key to `manifest.json`, but I just checked a recent extension from the add-ons store and you actually want `browser_specific_settings` instead. So add this to `manifest.json`:
    ```json
    "browser_specific_settings": {
      "gecko": {
        "id": "blahblah@blahblah.org"
      }
    }
    ```
5. Also you need to change `manifest_version` to be `2`. Because according to [the MDN docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version):
    > Currently, this must always be 2.
6. Rename the ZIP to XPI.
7. Now, installing this is going to be extremely annoying. First, you must go to `about:config` then change `xpinstall.signatures.required` to `false`.
8. Then, you *need to install Firefox ESR* (Extended Support Release) because ***Mozilla are a bunch of wusses and don't trust you to install unsigned add-ons on their official "Release" channel***. To say this is extremely annoying is beyond an understatement. There are some hacks around this, but I just installed ESR because my Linux distro (NixOS) has completely generic support for multiple versions of one package and I can just do `nix-shell -p firefox-esr` then run `firefox` to run ESR.
9. Go to the add-ons management page, click the cog, click `Install Add-on From File...`, then select the XPI.

---

I do want to reiterate, **none of this is needed** and I just did all this to confirm that it works on Firefox as-is, just needing a format conversion from CRX to XPI and all that other jazz (which conveniently [addons.mozilla.org](https://addons.mozilla.org/) will do for you automatically). So, yeah, there should be no reason why this extension isn't on the Firefox store.

**Comment by chrisyfrisky** [comment]
So it's been a couple days... if you're not available to upload it to the add-on store, are you fine with me uploading it myself?

**Comment by DeGrandis** [comment]
No.  I am not fine with that.  That is a disrespectful question to ask, especially since I do not know you and you have no history with this project.  Your rudeness and snark will not get you very far.  Your above comment states you already got it to work on your machine.  Why are you adamant about adding this to that store?  Out of the 4 years and tens of thousands of users, you are the only one to ever ask about Firefox.

**Comment by chrisyfrisky** [comment]
I apologize for being disrespectful. I thought it would be rude to ask again and demand bandwidth from you that you stated you didn't have, since you hadn't replied for a couple of days.

> Your above comment states you already got it to work on your machine. Why are you adamant about adding this to that store?

Because it's not ideal that I have to manually convert the file and run an unsigned, unverified extension on my browser? Not to mention needing to switch to specific browser versions to enable unsigned extensions in the first place. If this was in the store, it'd be automatically signed and verified and would be able to be installed for all supported browser releases. As a bonus, the file is already able to be uploaded to the store as-is, so no work needs to be done except just uploading the extension and going through the process.

> Out of the 4 years and tens of thousands of users, you are the only one to ever ask about Firefox.

Well, I'm sure there's many Firefox users that would've used this extension but couldn't, they just did not make a GitHub issue about it. They may have used alternate solutions instead, such as installing Stylus to use the various Canvas dark style themes on userstyles.org (which are all varying degrees of not great), or using the Owl extension, or something else. They may not have been even aware that this extension existed in the first place. Or they just silently switched to Chrome, idk.

**Comment by DeGrandis** [comment]
https://addons.mozilla.org/en-US/firefox/addon/canvas-dark-mode/
